#!/bin/bash

#$ -N fruit_fly_unet
#$ -P ec523bn
#$ -l h_rt=12:00:00
#$ -l gpu_c=6.0
#$ -j y
#$ -m e

module load python3/3.12.4
rm -rf .venv
python3 -m venv .venv
source /projectnb/ec523bn/students/liamh/fruit-fly-tracker/self_supervision_detection/.venv/bin/activate
pip install --upgrade pip==25.2
pip install numpy torch torchvision PIL matplotlib segmentation_models_pytorch
cd ..
pip install -e .
cd self_supervision_detection

python unet.py -i /projectnb/ec523bn/students/liamh/fly_data/synthetic_data/train/images/ -l /projectnb/ec523bn/students/liamh/fly_data/synthetic_data/train/masks/ -b /projectnb/ec523bn/students/liamh/fly_data/synthetic_data/backgrounds/ -o unet_output/

