#!/bin/bash

#$ -N fruit_fly_unet
#$ -P ec523bn
#$ -l h_rt=12:00:00
#$ -l gpu_c=6.0
#$ -j y
#$ -m e

module load python3/3.10.12
source /projectnb/ec523bn/students/liamh/fruit-fly-tracker/self_supervision_detection/.venv/bin/activate
pip install -r requirements.txt

python unet.py -i /projectnb/ec523bn/students/liamh/fly_data/synthetic_data/train/images/ -l /projectnb/ec523bn/students/liamh/fly_data/synthetic_data/train/masks/ -b /projectnb/ec523bn/students/liamh/fly_data/synthetic_data/backgrounds/

